<?php

/**
 * @file
 * Contains wizard_medicamentos.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function wizard_medicamentos_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the wizard_medicamentos module.
    case 'help.page.wizard_medicamentos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Wizard Medicamentos Step Form') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function wizard_medicamentos_theme()
{
  $theme = [];

  return $theme;
}
